export const POST_AD_REQUEST = "POST_AD_REQUEST";
export const POST_AD_SUCCESS = "POST_AD_SUCCESS";
export const POST_AD_FAILURE = "POST_AD_FAILURE";
export const UNSET_SUCCESS_STATUS = "UNSET_SUCCESS_STATUS";
