export const GET_CARS_REQUEST = "GET_CARS_REQUEST"
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS"
export const GET_CARS_FAILURE = "GET_CARS_FAILURE"

export const GET_MOTORCYCLES_REQUEST = "GET_MOTORCYCLES_REQUEST"
export const GET_MOTORCYCLES_SUCCESS = "GET_MOTORCYCLES_SUCCESS"
export const GET_MOTORCYCLES_FAILURE = "GET_MOTORCYCLES_FAILURE"

export const GET_MOBILE_REQUEST = "GET_MOBILE_REQUEST"
export const GET_MOBILE_SUCCESS = "GET_MOBILE_SUCCESS"
export const GET_MOBILE_FAILURE = "GET_MOBILE_FAILURE"

export const GET_SALES_HOUSE_REQUEST = "GET_SALES_HOUSE_REQUEST"
export const GET_SALES_HOUSE_SUCCESS = "GET_SALES_HOUSE_SUCCESS"
export const GET_SALES_HOUSE_FAILURE = "GET_SALES_HOUSE_FAILURE"

export const GET_SCOOTERS_REQUEST = "GET_SCOOTERS_REQUEST"
export const GET_SCOOTERS_SUCCESS = "GET_SCOOTERS_SUCCESS"
export const GET_SCOOTERS_FAILURE = "GET_SCOOTERS_FAILURE"

export const GET_COMMERICAL_REQUEST = "GET_COMMERICAL_REQUEST"
export const GET_COMMERICAL_SUCCESS = "GET_COMMERICAL_SUCCESS"
export const GET_COMMERICAL_FAILURE = "GET_COMMERICAL_FAILURE"

export const GET_RENT_HOUSE_REQUEST = "GET_RENT_HOUSE_REQUEST"
export const GET_RENT_HOUSE_SUCCESS = "GET_RENT_HOUSE_SUCCESS"
export const GET_RENT_HOUSE_FAILURE = "GET_RENT_HOUSE_FAILURE"

export const GET_FRESH_RECOMMENDATION_REQUEST = "GET_FRESH_RECOMMENDATION_REQUEST"
export const GET_FRESH_RECOMMENDATION_SUCCESS = "GET_FRESH_RECOMMENDATION_SUCCESS"
export const GET_FRESH_RECOMMENDATION_FAILURE = "GET_FRESH_RECOMMENDATION_FAILURE"
