export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const AUTH_STATE_TRUE = "AUTH_STATE_TRUE";
export const AUTH_STATE_FALSE = "AUTH_STATE_FALSE";