export const GET_DYNAMIC_DATA_REQUEST = "GET_DYNAMIC_DATA_REQUEST";
export const GET_DYNAMIC_DATA_SUCCESS = "GET_DYNAMIC_DATA_SUCCESS";
export const GET_DYNAMIC_DATA_FAILURE = "GET_DYNAMIC_DATA_FAILURE";